/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package ci.smile.system.manager.obf.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// ACTION
	VIEW_ACTION("VIEW_ACTION"),	
	CREATE_ACTION("CREATE_ACTION"),
	UPDATE_ACTION("UPDATE_ACTION"),
	DELETE_ACTION("DELETE_ACTION"),
	// ATTRIBUT
	VIEW_ATTRIBUT("VIEW_ATTRIBUT"),	
	CREATE_ATTRIBUT("CREATE_ATTRIBUT"),
	UPDATE_ATTRIBUT("UPDATE_ATTRIBUT"),
	DELETE_ATTRIBUT("DELETE_ATTRIBUT"),
	// COEFFICIENT_MODELE
	VIEW_COEFFICIENT_MODELE("VIEW_COEFFICIENT_MODELE"),	
	CREATE_COEFFICIENT_MODELE("CREATE_COEFFICIENT_MODELE"),
	UPDATE_COEFFICIENT_MODELE("UPDATE_COEFFICIENT_MODELE"),
	DELETE_COEFFICIENT_MODELE("DELETE_COEFFICIENT_MODELE"),
	// COMPTE
	VIEW_COMPTE("VIEW_COMPTE"),	
	CREATE_COMPTE("CREATE_COMPTE"),
	UPDATE_COMPTE("UPDATE_COMPTE"),
	DELETE_COMPTE("DELETE_COMPTE"),
	// GROUPE
	VIEW_GROUPE("VIEW_GROUPE"),	
	CREATE_GROUPE("CREATE_GROUPE"),
	UPDATE_GROUPE("UPDATE_GROUPE"),
	DELETE_GROUPE("DELETE_GROUPE"),
	// GROUPE_RADIUS
	VIEW_GROUPE_RADIUS("VIEW_GROUPE_RADIUS"),	
	CREATE_GROUPE_RADIUS("CREATE_GROUPE_RADIUS"),
	UPDATE_GROUPE_RADIUS("UPDATE_GROUPE_RADIUS"),
	DELETE_GROUPE_RADIUS("DELETE_GROUPE_RADIUS"),
	// LOCALISATION
	VIEW_LOCALISATION("VIEW_LOCALISATION"),	
	CREATE_LOCALISATION("CREATE_LOCALISATION"),
	UPDATE_LOCALISATION("UPDATE_LOCALISATION"),
	DELETE_LOCALISATION("DELETE_LOCALISATION"),
	// MENUS
	VIEW_MENUS("VIEW_MENUS"),	
	CREATE_MENUS("CREATE_MENUS"),
	UPDATE_MENUS("UPDATE_MENUS"),
	DELETE_MENUS("DELETE_MENUS"),
	// MODELE
	VIEW_MODELE("VIEW_MODELE"),	
	CREATE_MODELE("CREATE_MODELE"),
	UPDATE_MODELE("UPDATE_MODELE"),
	DELETE_MODELE("DELETE_MODELE"),
	// MODULE
	VIEW_MODULE("VIEW_MODULE"),	
	CREATE_MODULE("CREATE_MODULE"),
	UPDATE_MODULE("UPDATE_MODULE"),
	DELETE_MODULE("DELETE_MODULE"),
	// OFFER
	VIEW_OFFER("VIEW_OFFER"),	
	CREATE_OFFER("CREATE_OFFER"),
	UPDATE_OFFER("UPDATE_OFFER"),
	DELETE_OFFER("DELETE_OFFER"),
	// OFFER_GROUPE
	VIEW_OFFER_GROUPE("VIEW_OFFER_GROUPE"),	
	CREATE_OFFER_GROUPE("CREATE_OFFER_GROUPE"),
	UPDATE_OFFER_GROUPE("UPDATE_OFFER_GROUPE"),
	DELETE_OFFER_GROUPE("DELETE_OFFER_GROUPE"),
	// OFFER_OLT
	VIEW_OFFER_OLT("VIEW_OFFER_OLT"),	
	CREATE_OFFER_OLT("CREATE_OFFER_OLT"),
	UPDATE_OFFER_OLT("UPDATE_OFFER_OLT"),
	DELETE_OFFER_OLT("DELETE_OFFER_OLT"),
	// PLATEFORME
	VIEW_PLATEFORME("VIEW_PLATEFORME"),	
	CREATE_PLATEFORME("CREATE_PLATEFORME"),
	UPDATE_PLATEFORME("UPDATE_PLATEFORME"),
	DELETE_PLATEFORME("DELETE_PLATEFORME"),
	// RADIUS
	VIEW_RADIUS("VIEW_RADIUS"),	
	CREATE_RADIUS("CREATE_RADIUS"),
	UPDATE_RADIUS("UPDATE_RADIUS"),
	DELETE_RADIUS("DELETE_RADIUS"),
	// ROLE
	VIEW_ROLE("VIEW_ROLE"),	
	CREATE_ROLE("CREATE_ROLE"),
	UPDATE_ROLE("UPDATE_ROLE"),
	DELETE_ROLE("DELETE_ROLE"),
	// ROLE_ACTION
	VIEW_ROLE_ACTION("VIEW_ROLE_ACTION"),	
	CREATE_ROLE_ACTION("CREATE_ROLE_ACTION"),
	UPDATE_ROLE_ACTION("UPDATE_ROLE_ACTION"),
	DELETE_ROLE_ACTION("DELETE_ROLE_ACTION"),
	// ROLE_USER
	VIEW_ROLE_USER("VIEW_ROLE_USER"),	
	CREATE_ROLE_USER("CREATE_ROLE_USER"),
	UPDATE_ROLE_USER("UPDATE_ROLE_USER"),
	DELETE_ROLE_USER("DELETE_ROLE_USER"),
	// TYPE_ATTRIBUT
	VIEW_TYPE_ATTRIBUT("VIEW_TYPE_ATTRIBUT"),	
	CREATE_TYPE_ATTRIBUT("CREATE_TYPE_ATTRIBUT"),
	UPDATE_TYPE_ATTRIBUT("UPDATE_TYPE_ATTRIBUT"),
	DELETE_TYPE_ATTRIBUT("DELETE_TYPE_ATTRIBUT"),
	// TYPE_OFFRE
	VIEW_TYPE_OFFRE("VIEW_TYPE_OFFRE"),	
	CREATE_TYPE_OFFRE("CREATE_TYPE_OFFRE"),
	UPDATE_TYPE_OFFRE("UPDATE_TYPE_OFFRE"),
	DELETE_TYPE_OFFRE("DELETE_TYPE_OFFRE"),
	
	// TYPE_OFFRE
	VIEW_ASSIGNATION("VIEW_ASSIGNATION"),	
	CREATE_ASSIGNATION("CREATE_ASSIGNATION"),
	UPDATE_ASSIGNATION("UPDATE_ASSIGNATION"),
	DELETE_ASSIGNATION("DELETE_ASSIGNATION"),
	// TYPE_OFFRE
	VIEW_CAUSE_GENERALE("VIEW_CAUSE_GENERALE"),	
	CREATE_CAUSE_GENERALE("CREATE_CAUSE_GENERALE"),
	UPDATE_CAUSE_GENERALE("UPDATE_CAUSE_GENERALE"),
	DELETE_CAUSE_GENERALE("DELETE_CAUSE_GENERALE"),
	// TYPE_OFFRE
	VIEW_CAUSE_SPECIFIQUE("VIEW_CAUSE_SPECIFIQUE"),	
	CREATE_CAUSE_SPECIFIQUE("CREATE_CAUSE_SPECIFIQUE"),
	UPDATE_CAUSE_SPECIFIQUE("UPDATE_CAUSE_SPECIFIQUE"),
	DELETE_CAUSE_SPECIFIQUE("DELETE_CAUSE_SPECIFIQUE"),
	// TYPE_OFFRE
	VIEW_CORBEILLE("VIEW_CORBEILLE"),	
	CREATE_CORBEILLE("CREATE_CORBEILLE"),
	UPDATE_CORBEILLE("UPDATE_CORBEILLE"),
	DELETE_CORBEILLE("DELETE_CORBEILLE"),
	// TYPE_OFFRE
	VIEW_QUALIFICATIF("VIEW_QUALIFICATIF"),	
	CREATE_QUALIFICATIF("CREATE_QUALIFICATIF"),
	UPDATE_QUALIFICATIF("UPDATE_QUALIFICATIF"),
	DELETE_QUALIFICATIF("DELETE_QUALIFICATIF"),
	
	// USER
	VIEW_USER("VIEW_USER"),	
	CREATE_USER("CREATE_USER"),
	UPDATE_USER("UPDATE_USER"),
	DELETE_USER("DELETE_USER");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
