/*
 * Created on 2019-12-19 ( Time 23:54:47 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.system.manager.obf.dao.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;

/**
 * Persistent class for entity stored in table "menus"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Data
@Table(name="action" )
public class Action implements Serializable, Cloneable {

	private static final long serialVersionUID = 1L;

	//----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	//----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="id", nullable=false)
	private Integer    id           ;


	//----------------------------------------------------------------------
	// ENTITY DATA FIELDS 
	//----------------------------------------------------------------------    
	@Column(name="libelle", length=255)
	private String     libelle      ;

	@Column(name="code", length=255)
	private String     code         ;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="created_at")
	private Date       createdAt    ;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="updated_at")
	private Date       updatedAt    ;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="deleted_at")
	private Date       deletedAt    ;


	@Column(name="is_locked")
	private Boolean    isLocked     ;

	@Column(name="created_by")
	private Integer    createdBy    ;

	@Column(name="updated_by")
	private Integer    updatedBy    ;

	@Column(name="deleted_by")
	private Integer    deletedBy    ;

	@Column(name="is_deleted")
	private Boolean    isDeleted    ;

	// "moduleId" (column "module_id") is not defined by itself because used as FK in a link 

	//----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	//----------------------------------------------------------------------
	@ManyToOne
	@JoinColumn(name="menus_id", referencedColumnName="id")
	private Menus menus      ;


	@ManyToOne
	@JoinColumn(name="parent_id", referencedColumnName="id")
	private Action parent      ;

	//----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	//----------------------------------------------------------------------
	public Action() {
		super();
	}







}
